components:
  schemas:
    Empty:
      type: object
    NewPet:
      properties:
        price:
          type: number
        type:
          $ref: '#/components/schemas/PetType'
      type: object
    NewPetResponse:
      properties:
        message:
          type: string
        pet:
          $ref: '#/components/schemas/Pet'
      type: object
    Pet:
      properties:
        id:
          type: integer
        price:
          type: number
        type:
          type: string
      type: object
    PetType:
      enum:
      - dog
      - cat
      - fish
      - bird
      - gecko
      type: string
    Pets:
      items:
        $ref: '#/components/schemas/Pet'
      type: array
info:
  description: Your first API with Amazon API Gateway. This is a sample API that integrates
    via HTTP with our demo Pet Store endpoints
  title: PetStore
  version: "2020-07-14T08:16:01Z"
openapi: 3.0.1
paths:
  /:
    get:
      responses:
        "200":
          content: {}
          description: 200 response
          headers:
            Content-Type:
              schema:
                type: string
  /pets:
    get:
      parameters:
      - in: query
        name: type
        schema:
          type: string
      - in: query
        name: page
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
    options:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: 200 response
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
    post:
      operationId: CreatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewPetResponse'
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /pets/{petId}:
    get:
      operationId: GetPet
      parameters:
      - in: path
        name: petId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
    options:
      parameters:
      - in: path
        name: petId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: 200 response
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
servers:
- url: https://lg9m4mu9qk.execute-api.us-east-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: /beta
