apiVersion: wso2.com/v1alpha1
kind: API
metadata:
  name:
spec:
  definition:
    swaggerconfigmapName:
    interceptors:
      ballerina:
      java:
    type: swagger
  replicas:
  mode: privateJet
  override: false
