config:
  http_timeout: 2500
  export_directory: .

environments:
  sample-env:
    api_manager_endpoint: sample-apim-endpoint
    registration_endpoint: sample-reg-endpoint
    token_endpoint: sample-token-endpoint
