config:
  http_request_timeout: 3600
  export_directory: /home/menuka/Documents/exported
environments:
  dev:
    api_manager_endpoint: https://172.21.0.1:9443
    registration_endpoint: https://localhost:9443/identity/connect/register
    token_endpoint: https://localhost:9443/oauth2/token
  testEnv:
    api_manager_endpoint: api_manager
    registration_endpoint: registration
    token_endpoint: token
