config:
  http_request_timeout: 3600
  export_directory: /home/menuka/Documents/exported
environments:
  dev:
    api_manager_endpoint: https://172.21.0.1:9443
    registration_endpoint: http://localhost:9763/client-registration/v0.11/register
    token_endpoint: https://172.21.0.1:8243/token
