config:
  http_request_timeout: 3600
  export_directory: /home/menuka/Documents/exported
environments:
  dev:
    api_manager_endpoint: https://localhost:9443
    api_import_export_endpoint:  https://localhost:9443/api-import-export-2.6.0-v0
    registration_endpoint: http://localhost:9763/client-registration/v0.14/register
    token_endpoint: https://localhost:8243/token
  gcloud1:
    api_manager_endpoint: https://104.196.50.59:9443
    registration_endpoint: http://104.196.50.59:9763/client-registration/v0.14/register
    token_endpoint: https://104.196.50.59:8243/token
